### ISSUE TITLE
Suggestion: Google OR-Tools

### ISSUE THREAD

**Issue by CPMOliveira** [frangio68/Min-Cost-Flow-Class#1]
Congratulations for the initiative!

I suggest incorporating these algorithms into the Google OR-Tools:
https://github.com/google/or-tools

**Comment by frangio68** [comment]
Thank you. However, they already have graph stuff.
I'd be happy to collaborate if I was required to put the code there, but I guess it should be their proposal, not mine. If you think this may be useful for some reason and want to suggest them to, feel very free.
